-- Run command: db2 -tvf call_function.sh

CONNECT TO TESTDB;

VALUES (MULTIPLY_UDF(NULL, NULL));
VALUES (MULTIPLY_UDF(NULL, 12));
VALUES (MULTIPLY_UDF(7, NULL));
VALUES (MULTIPLY_UDF(28, 347));
VALUES (MULTIPLY_UDF(-96, 42));

CONNECT RESET;
